//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.GameShopWarehouseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameShopWarehouseService.IGameShopWarehouse")]
    public interface IGameShopWarehouse {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameShopWarehouse/GetAllItems", ReplyAction="http://tempuri.org/IGameShopWarehouse/GetAllItemsResponse")]
        EFGameShopDatabase.Models.Item[] GetAllItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameShopWarehouse/GetAllItems", ReplyAction="http://tempuri.org/IGameShopWarehouse/GetAllItemsResponse")]
        System.Threading.Tasks.Task<EFGameShopDatabase.Models.Item[]> GetAllItemsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameShopWarehouseChannel : TestClient.GameShopWarehouseService.IGameShopWarehouse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameShopWarehouseClient : System.ServiceModel.ClientBase<TestClient.GameShopWarehouseService.IGameShopWarehouse>, TestClient.GameShopWarehouseService.IGameShopWarehouse {
        
        public GameShopWarehouseClient() {
        }
        
        public GameShopWarehouseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameShopWarehouseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameShopWarehouseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameShopWarehouseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EFGameShopDatabase.Models.Item[] GetAllItems() {
            return base.Channel.GetAllItems();
        }
        
        public System.Threading.Tasks.Task<EFGameShopDatabase.Models.Item[]> GetAllItemsAsync() {
            return base.Channel.GetAllItemsAsync();
        }
    }
}
